// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package com.nhekfqn.sample.server.proto;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.nhekfqn.sample.server.proto.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ping = 1;</code>
     */
    ping(0, 1),
    /**
     * <code>pong = 2;</code>
     */
    pong(1, 2),
    ;

    /**
     * <code>ping = 1;</code>
     */
    public static final int ping_VALUE = 1;
    /**
     * <code>pong = 2;</code>
     */
    public static final int pong_VALUE = 2;


    public final int getNumber() { return value; }

    public static MessageType valueOf(int value) {
      switch (value) {
        case 1: return ping;
        case 2: return pong;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.nhekfqn.sample.server.proto.Protocol.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MessageType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.nhekfqn.sample.server.proto.MessageType)
  }

  public interface BaseMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.nhekfqn.sample.server.proto.MessageType messageType = 1;
    /**
     * <code>required .com.nhekfqn.sample.server.proto.MessageType messageType = 1;</code>
     */
    boolean hasMessageType();
    /**
     * <code>required .com.nhekfqn.sample.server.proto.MessageType messageType = 1;</code>
     */
    com.nhekfqn.sample.server.proto.Protocol.MessageType getMessageType();

    // optional .com.nhekfqn.sample.server.proto.Ping ping = 2;
    /**
     * <code>optional .com.nhekfqn.sample.server.proto.Ping ping = 2;</code>
     */
    boolean hasPing();
    /**
     * <code>optional .com.nhekfqn.sample.server.proto.Ping ping = 2;</code>
     */
    com.nhekfqn.sample.server.proto.Protocol.Ping getPing();
    /**
     * <code>optional .com.nhekfqn.sample.server.proto.Ping ping = 2;</code>
     */
    com.nhekfqn.sample.server.proto.Protocol.PingOrBuilder getPingOrBuilder();

    // optional .com.nhekfqn.sample.server.proto.Pong pong = 3;
    /**
     * <code>optional .com.nhekfqn.sample.server.proto.Pong pong = 3;</code>
     */
    boolean hasPong();
    /**
     * <code>optional .com.nhekfqn.sample.server.proto.Pong pong = 3;</code>
     */
    com.nhekfqn.sample.server.proto.Protocol.Pong getPong();
    /**
     * <code>optional .com.nhekfqn.sample.server.proto.Pong pong = 3;</code>
     */
    com.nhekfqn.sample.server.proto.Protocol.PongOrBuilder getPongOrBuilder();
  }
  /**
   * Protobuf type {@code com.nhekfqn.sample.server.proto.BaseMessage}
   */
  public static final class BaseMessage extends
      com.google.protobuf.GeneratedMessage
      implements BaseMessageOrBuilder {
    // Use BaseMessage.newBuilder() to construct.
    private BaseMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BaseMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BaseMessage defaultInstance;
    public static BaseMessage getDefaultInstance() {
      return defaultInstance;
    }

    public BaseMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BaseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.nhekfqn.sample.server.proto.Protocol.MessageType value = com.nhekfqn.sample.server.proto.Protocol.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                messageType_ = value;
              }
              break;
            }
            case 18: {
              com.nhekfqn.sample.server.proto.Protocol.Ping.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = ping_.toBuilder();
              }
              ping_ = input.readMessage(com.nhekfqn.sample.server.proto.Protocol.Ping.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ping_);
                ping_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.nhekfqn.sample.server.proto.Protocol.Pong.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = pong_.toBuilder();
              }
              pong_ = input.readMessage(com.nhekfqn.sample.server.proto.Protocol.Pong.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pong_);
                pong_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nhekfqn.sample.server.proto.Protocol.internal_static_com_nhekfqn_sample_server_proto_BaseMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nhekfqn.sample.server.proto.Protocol.internal_static_com_nhekfqn_sample_server_proto_BaseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nhekfqn.sample.server.proto.Protocol.BaseMessage.class, com.nhekfqn.sample.server.proto.Protocol.BaseMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<BaseMessage> PARSER =
        new com.google.protobuf.AbstractParser<BaseMessage>() {
      public BaseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BaseMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.nhekfqn.sample.server.proto.MessageType messageType = 1;
    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private com.nhekfqn.sample.server.proto.Protocol.MessageType messageType_;
    /**
     * <code>required .com.nhekfqn.sample.server.proto.MessageType messageType = 1;</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.nhekfqn.sample.server.proto.MessageType messageType = 1;</code>
     */
    public com.nhekfqn.sample.server.proto.Protocol.MessageType getMessageType() {
      return messageType_;
    }

    // optional .com.nhekfqn.sample.server.proto.Ping ping = 2;
    public static final int PING_FIELD_NUMBER = 2;
    private com.nhekfqn.sample.server.proto.Protocol.Ping ping_;
    /**
     * <code>optional .com.nhekfqn.sample.server.proto.Ping ping = 2;</code>
     */
    public boolean hasPing() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.nhekfqn.sample.server.proto.Ping ping = 2;</code>
     */
    public com.nhekfqn.sample.server.proto.Protocol.Ping getPing() {
      return ping_;
    }
    /**
     * <code>optional .com.nhekfqn.sample.server.proto.Ping ping = 2;</code>
     */
    public com.nhekfqn.sample.server.proto.Protocol.PingOrBuilder getPingOrBuilder() {
      return ping_;
    }

    // optional .com.nhekfqn.sample.server.proto.Pong pong = 3;
    public static final int PONG_FIELD_NUMBER = 3;
    private com.nhekfqn.sample.server.proto.Protocol.Pong pong_;
    /**
     * <code>optional .com.nhekfqn.sample.server.proto.Pong pong = 3;</code>
     */
    public boolean hasPong() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.nhekfqn.sample.server.proto.Pong pong = 3;</code>
     */
    public com.nhekfqn.sample.server.proto.Protocol.Pong getPong() {
      return pong_;
    }
    /**
     * <code>optional .com.nhekfqn.sample.server.proto.Pong pong = 3;</code>
     */
    public com.nhekfqn.sample.server.proto.Protocol.PongOrBuilder getPongOrBuilder() {
      return pong_;
    }

    private void initFields() {
      messageType_ = com.nhekfqn.sample.server.proto.Protocol.MessageType.ping;
      ping_ = com.nhekfqn.sample.server.proto.Protocol.Ping.getDefaultInstance();
      pong_ = com.nhekfqn.sample.server.proto.Protocol.Pong.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMessageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasPing()) {
        if (!getPing().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasPong()) {
        if (!getPong().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, ping_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, pong_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, ping_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, pong_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.nhekfqn.sample.server.proto.Protocol.BaseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.BaseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.BaseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.BaseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.BaseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.BaseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.BaseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.BaseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.BaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.BaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.nhekfqn.sample.server.proto.Protocol.BaseMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.nhekfqn.sample.server.proto.BaseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.nhekfqn.sample.server.proto.Protocol.BaseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nhekfqn.sample.server.proto.Protocol.internal_static_com_nhekfqn_sample_server_proto_BaseMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nhekfqn.sample.server.proto.Protocol.internal_static_com_nhekfqn_sample_server_proto_BaseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nhekfqn.sample.server.proto.Protocol.BaseMessage.class, com.nhekfqn.sample.server.proto.Protocol.BaseMessage.Builder.class);
      }

      // Construct using com.nhekfqn.sample.server.proto.Protocol.BaseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPingFieldBuilder();
          getPongFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageType_ = com.nhekfqn.sample.server.proto.Protocol.MessageType.ping;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (pingBuilder_ == null) {
          ping_ = com.nhekfqn.sample.server.proto.Protocol.Ping.getDefaultInstance();
        } else {
          pingBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (pongBuilder_ == null) {
          pong_ = com.nhekfqn.sample.server.proto.Protocol.Pong.getDefaultInstance();
        } else {
          pongBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nhekfqn.sample.server.proto.Protocol.internal_static_com_nhekfqn_sample_server_proto_BaseMessage_descriptor;
      }

      public com.nhekfqn.sample.server.proto.Protocol.BaseMessage getDefaultInstanceForType() {
        return com.nhekfqn.sample.server.proto.Protocol.BaseMessage.getDefaultInstance();
      }

      public com.nhekfqn.sample.server.proto.Protocol.BaseMessage build() {
        com.nhekfqn.sample.server.proto.Protocol.BaseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nhekfqn.sample.server.proto.Protocol.BaseMessage buildPartial() {
        com.nhekfqn.sample.server.proto.Protocol.BaseMessage result = new com.nhekfqn.sample.server.proto.Protocol.BaseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (pingBuilder_ == null) {
          result.ping_ = ping_;
        } else {
          result.ping_ = pingBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (pongBuilder_ == null) {
          result.pong_ = pong_;
        } else {
          result.pong_ = pongBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nhekfqn.sample.server.proto.Protocol.BaseMessage) {
          return mergeFrom((com.nhekfqn.sample.server.proto.Protocol.BaseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nhekfqn.sample.server.proto.Protocol.BaseMessage other) {
        if (other == com.nhekfqn.sample.server.proto.Protocol.BaseMessage.getDefaultInstance()) return this;
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasPing()) {
          mergePing(other.getPing());
        }
        if (other.hasPong()) {
          mergePong(other.getPong());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessageType()) {
          
          return false;
        }
        if (hasPing()) {
          if (!getPing().isInitialized()) {
            
            return false;
          }
        }
        if (hasPong()) {
          if (!getPong().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nhekfqn.sample.server.proto.Protocol.BaseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nhekfqn.sample.server.proto.Protocol.BaseMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.nhekfqn.sample.server.proto.MessageType messageType = 1;
      private com.nhekfqn.sample.server.proto.Protocol.MessageType messageType_ = com.nhekfqn.sample.server.proto.Protocol.MessageType.ping;
      /**
       * <code>required .com.nhekfqn.sample.server.proto.MessageType messageType = 1;</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.nhekfqn.sample.server.proto.MessageType messageType = 1;</code>
       */
      public com.nhekfqn.sample.server.proto.Protocol.MessageType getMessageType() {
        return messageType_;
      }
      /**
       * <code>required .com.nhekfqn.sample.server.proto.MessageType messageType = 1;</code>
       */
      public Builder setMessageType(com.nhekfqn.sample.server.proto.Protocol.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.nhekfqn.sample.server.proto.MessageType messageType = 1;</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = com.nhekfqn.sample.server.proto.Protocol.MessageType.ping;
        onChanged();
        return this;
      }

      // optional .com.nhekfqn.sample.server.proto.Ping ping = 2;
      private com.nhekfqn.sample.server.proto.Protocol.Ping ping_ = com.nhekfqn.sample.server.proto.Protocol.Ping.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.nhekfqn.sample.server.proto.Protocol.Ping, com.nhekfqn.sample.server.proto.Protocol.Ping.Builder, com.nhekfqn.sample.server.proto.Protocol.PingOrBuilder> pingBuilder_;
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.Ping ping = 2;</code>
       */
      public boolean hasPing() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.Ping ping = 2;</code>
       */
      public com.nhekfqn.sample.server.proto.Protocol.Ping getPing() {
        if (pingBuilder_ == null) {
          return ping_;
        } else {
          return pingBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.Ping ping = 2;</code>
       */
      public Builder setPing(com.nhekfqn.sample.server.proto.Protocol.Ping value) {
        if (pingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ping_ = value;
          onChanged();
        } else {
          pingBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.Ping ping = 2;</code>
       */
      public Builder setPing(
          com.nhekfqn.sample.server.proto.Protocol.Ping.Builder builderForValue) {
        if (pingBuilder_ == null) {
          ping_ = builderForValue.build();
          onChanged();
        } else {
          pingBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.Ping ping = 2;</code>
       */
      public Builder mergePing(com.nhekfqn.sample.server.proto.Protocol.Ping value) {
        if (pingBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              ping_ != com.nhekfqn.sample.server.proto.Protocol.Ping.getDefaultInstance()) {
            ping_ =
              com.nhekfqn.sample.server.proto.Protocol.Ping.newBuilder(ping_).mergeFrom(value).buildPartial();
          } else {
            ping_ = value;
          }
          onChanged();
        } else {
          pingBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.Ping ping = 2;</code>
       */
      public Builder clearPing() {
        if (pingBuilder_ == null) {
          ping_ = com.nhekfqn.sample.server.proto.Protocol.Ping.getDefaultInstance();
          onChanged();
        } else {
          pingBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.Ping ping = 2;</code>
       */
      public com.nhekfqn.sample.server.proto.Protocol.Ping.Builder getPingBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPingFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.Ping ping = 2;</code>
       */
      public com.nhekfqn.sample.server.proto.Protocol.PingOrBuilder getPingOrBuilder() {
        if (pingBuilder_ != null) {
          return pingBuilder_.getMessageOrBuilder();
        } else {
          return ping_;
        }
      }
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.Ping ping = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.nhekfqn.sample.server.proto.Protocol.Ping, com.nhekfqn.sample.server.proto.Protocol.Ping.Builder, com.nhekfqn.sample.server.proto.Protocol.PingOrBuilder> 
          getPingFieldBuilder() {
        if (pingBuilder_ == null) {
          pingBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.nhekfqn.sample.server.proto.Protocol.Ping, com.nhekfqn.sample.server.proto.Protocol.Ping.Builder, com.nhekfqn.sample.server.proto.Protocol.PingOrBuilder>(
                  ping_,
                  getParentForChildren(),
                  isClean());
          ping_ = null;
        }
        return pingBuilder_;
      }

      // optional .com.nhekfqn.sample.server.proto.Pong pong = 3;
      private com.nhekfqn.sample.server.proto.Protocol.Pong pong_ = com.nhekfqn.sample.server.proto.Protocol.Pong.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.nhekfqn.sample.server.proto.Protocol.Pong, com.nhekfqn.sample.server.proto.Protocol.Pong.Builder, com.nhekfqn.sample.server.proto.Protocol.PongOrBuilder> pongBuilder_;
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.Pong pong = 3;</code>
       */
      public boolean hasPong() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.Pong pong = 3;</code>
       */
      public com.nhekfqn.sample.server.proto.Protocol.Pong getPong() {
        if (pongBuilder_ == null) {
          return pong_;
        } else {
          return pongBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.Pong pong = 3;</code>
       */
      public Builder setPong(com.nhekfqn.sample.server.proto.Protocol.Pong value) {
        if (pongBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pong_ = value;
          onChanged();
        } else {
          pongBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.Pong pong = 3;</code>
       */
      public Builder setPong(
          com.nhekfqn.sample.server.proto.Protocol.Pong.Builder builderForValue) {
        if (pongBuilder_ == null) {
          pong_ = builderForValue.build();
          onChanged();
        } else {
          pongBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.Pong pong = 3;</code>
       */
      public Builder mergePong(com.nhekfqn.sample.server.proto.Protocol.Pong value) {
        if (pongBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              pong_ != com.nhekfqn.sample.server.proto.Protocol.Pong.getDefaultInstance()) {
            pong_ =
              com.nhekfqn.sample.server.proto.Protocol.Pong.newBuilder(pong_).mergeFrom(value).buildPartial();
          } else {
            pong_ = value;
          }
          onChanged();
        } else {
          pongBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.Pong pong = 3;</code>
       */
      public Builder clearPong() {
        if (pongBuilder_ == null) {
          pong_ = com.nhekfqn.sample.server.proto.Protocol.Pong.getDefaultInstance();
          onChanged();
        } else {
          pongBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.Pong pong = 3;</code>
       */
      public com.nhekfqn.sample.server.proto.Protocol.Pong.Builder getPongBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getPongFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.Pong pong = 3;</code>
       */
      public com.nhekfqn.sample.server.proto.Protocol.PongOrBuilder getPongOrBuilder() {
        if (pongBuilder_ != null) {
          return pongBuilder_.getMessageOrBuilder();
        } else {
          return pong_;
        }
      }
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.Pong pong = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.nhekfqn.sample.server.proto.Protocol.Pong, com.nhekfqn.sample.server.proto.Protocol.Pong.Builder, com.nhekfqn.sample.server.proto.Protocol.PongOrBuilder> 
          getPongFieldBuilder() {
        if (pongBuilder_ == null) {
          pongBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.nhekfqn.sample.server.proto.Protocol.Pong, com.nhekfqn.sample.server.proto.Protocol.Pong.Builder, com.nhekfqn.sample.server.proto.Protocol.PongOrBuilder>(
                  pong_,
                  getParentForChildren(),
                  isClean());
          pong_ = null;
        }
        return pongBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.nhekfqn.sample.server.proto.BaseMessage)
    }

    static {
      defaultInstance = new BaseMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.nhekfqn.sample.server.proto.BaseMessage)
  }

  public interface PingOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .com.nhekfqn.sample.server.proto.MessageType messageType = 1 [default = ping];
    /**
     * <code>optional .com.nhekfqn.sample.server.proto.MessageType messageType = 1 [default = ping];</code>
     */
    boolean hasMessageType();
    /**
     * <code>optional .com.nhekfqn.sample.server.proto.MessageType messageType = 1 [default = ping];</code>
     */
    com.nhekfqn.sample.server.proto.Protocol.MessageType getMessageType();

    // required string userId = 2;
    /**
     * <code>required string userId = 2;</code>
     */
    boolean hasUserId();
    /**
     * <code>required string userId = 2;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>required string userId = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();
  }
  /**
   * Protobuf type {@code com.nhekfqn.sample.server.proto.Ping}
   */
  public static final class Ping extends
      com.google.protobuf.GeneratedMessage
      implements PingOrBuilder {
    // Use Ping.newBuilder() to construct.
    private Ping(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Ping(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Ping defaultInstance;
    public static Ping getDefaultInstance() {
      return defaultInstance;
    }

    public Ping getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Ping(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.nhekfqn.sample.server.proto.Protocol.MessageType value = com.nhekfqn.sample.server.proto.Protocol.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                messageType_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              userId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nhekfqn.sample.server.proto.Protocol.internal_static_com_nhekfqn_sample_server_proto_Ping_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nhekfqn.sample.server.proto.Protocol.internal_static_com_nhekfqn_sample_server_proto_Ping_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nhekfqn.sample.server.proto.Protocol.Ping.class, com.nhekfqn.sample.server.proto.Protocol.Ping.Builder.class);
    }

    public static com.google.protobuf.Parser<Ping> PARSER =
        new com.google.protobuf.AbstractParser<Ping>() {
      public Ping parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Ping(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Ping> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .com.nhekfqn.sample.server.proto.MessageType messageType = 1 [default = ping];
    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private com.nhekfqn.sample.server.proto.Protocol.MessageType messageType_;
    /**
     * <code>optional .com.nhekfqn.sample.server.proto.MessageType messageType = 1 [default = ping];</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.nhekfqn.sample.server.proto.MessageType messageType = 1 [default = ping];</code>
     */
    public com.nhekfqn.sample.server.proto.Protocol.MessageType getMessageType() {
      return messageType_;
    }

    // required string userId = 2;
    public static final int USERID_FIELD_NUMBER = 2;
    private java.lang.Object userId_;
    /**
     * <code>required string userId = 2;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string userId = 2;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      messageType_ = com.nhekfqn.sample.server.proto.Protocol.MessageType.ping;
      userId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUserIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUserIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.nhekfqn.sample.server.proto.Protocol.Ping parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.Ping parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.Ping parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.Ping parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.Ping parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.Ping parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.Ping parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.Ping parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.Ping parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.Ping parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.nhekfqn.sample.server.proto.Protocol.Ping prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.nhekfqn.sample.server.proto.Ping}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.nhekfqn.sample.server.proto.Protocol.PingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nhekfqn.sample.server.proto.Protocol.internal_static_com_nhekfqn_sample_server_proto_Ping_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nhekfqn.sample.server.proto.Protocol.internal_static_com_nhekfqn_sample_server_proto_Ping_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nhekfqn.sample.server.proto.Protocol.Ping.class, com.nhekfqn.sample.server.proto.Protocol.Ping.Builder.class);
      }

      // Construct using com.nhekfqn.sample.server.proto.Protocol.Ping.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageType_ = com.nhekfqn.sample.server.proto.Protocol.MessageType.ping;
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nhekfqn.sample.server.proto.Protocol.internal_static_com_nhekfqn_sample_server_proto_Ping_descriptor;
      }

      public com.nhekfqn.sample.server.proto.Protocol.Ping getDefaultInstanceForType() {
        return com.nhekfqn.sample.server.proto.Protocol.Ping.getDefaultInstance();
      }

      public com.nhekfqn.sample.server.proto.Protocol.Ping build() {
        com.nhekfqn.sample.server.proto.Protocol.Ping result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nhekfqn.sample.server.proto.Protocol.Ping buildPartial() {
        com.nhekfqn.sample.server.proto.Protocol.Ping result = new com.nhekfqn.sample.server.proto.Protocol.Ping(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userId_ = userId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nhekfqn.sample.server.proto.Protocol.Ping) {
          return mergeFrom((com.nhekfqn.sample.server.proto.Protocol.Ping)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nhekfqn.sample.server.proto.Protocol.Ping other) {
        if (other == com.nhekfqn.sample.server.proto.Protocol.Ping.getDefaultInstance()) return this;
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasUserId()) {
          bitField0_ |= 0x00000002;
          userId_ = other.userId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nhekfqn.sample.server.proto.Protocol.Ping parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nhekfqn.sample.server.proto.Protocol.Ping) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.nhekfqn.sample.server.proto.MessageType messageType = 1 [default = ping];
      private com.nhekfqn.sample.server.proto.Protocol.MessageType messageType_ = com.nhekfqn.sample.server.proto.Protocol.MessageType.ping;
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.MessageType messageType = 1 [default = ping];</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.MessageType messageType = 1 [default = ping];</code>
       */
      public com.nhekfqn.sample.server.proto.Protocol.MessageType getMessageType() {
        return messageType_;
      }
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.MessageType messageType = 1 [default = ping];</code>
       */
      public Builder setMessageType(com.nhekfqn.sample.server.proto.Protocol.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.MessageType messageType = 1 [default = ping];</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = com.nhekfqn.sample.server.proto.Protocol.MessageType.ping;
        onChanged();
        return this;
      }

      // required string userId = 2;
      private java.lang.Object userId_ = "";
      /**
       * <code>required string userId = 2;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string userId = 2;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userId = 2;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userId = 2;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>required string userId = 2;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.nhekfqn.sample.server.proto.Ping)
    }

    static {
      defaultInstance = new Ping(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.nhekfqn.sample.server.proto.Ping)
  }

  public interface PongOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .com.nhekfqn.sample.server.proto.MessageType messageType = 1 [default = pong];
    /**
     * <code>optional .com.nhekfqn.sample.server.proto.MessageType messageType = 1 [default = pong];</code>
     */
    boolean hasMessageType();
    /**
     * <code>optional .com.nhekfqn.sample.server.proto.MessageType messageType = 1 [default = pong];</code>
     */
    com.nhekfqn.sample.server.proto.Protocol.MessageType getMessageType();

    // required int32 n = 2;
    /**
     * <code>required int32 n = 2;</code>
     */
    boolean hasN();
    /**
     * <code>required int32 n = 2;</code>
     */
    int getN();
  }
  /**
   * Protobuf type {@code com.nhekfqn.sample.server.proto.Pong}
   */
  public static final class Pong extends
      com.google.protobuf.GeneratedMessage
      implements PongOrBuilder {
    // Use Pong.newBuilder() to construct.
    private Pong(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Pong(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Pong defaultInstance;
    public static Pong getDefaultInstance() {
      return defaultInstance;
    }

    public Pong getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Pong(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.nhekfqn.sample.server.proto.Protocol.MessageType value = com.nhekfqn.sample.server.proto.Protocol.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                messageType_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              n_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nhekfqn.sample.server.proto.Protocol.internal_static_com_nhekfqn_sample_server_proto_Pong_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nhekfqn.sample.server.proto.Protocol.internal_static_com_nhekfqn_sample_server_proto_Pong_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nhekfqn.sample.server.proto.Protocol.Pong.class, com.nhekfqn.sample.server.proto.Protocol.Pong.Builder.class);
    }

    public static com.google.protobuf.Parser<Pong> PARSER =
        new com.google.protobuf.AbstractParser<Pong>() {
      public Pong parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Pong(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Pong> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .com.nhekfqn.sample.server.proto.MessageType messageType = 1 [default = pong];
    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private com.nhekfqn.sample.server.proto.Protocol.MessageType messageType_;
    /**
     * <code>optional .com.nhekfqn.sample.server.proto.MessageType messageType = 1 [default = pong];</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.nhekfqn.sample.server.proto.MessageType messageType = 1 [default = pong];</code>
     */
    public com.nhekfqn.sample.server.proto.Protocol.MessageType getMessageType() {
      return messageType_;
    }

    // required int32 n = 2;
    public static final int N_FIELD_NUMBER = 2;
    private int n_;
    /**
     * <code>required int32 n = 2;</code>
     */
    public boolean hasN() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 n = 2;</code>
     */
    public int getN() {
      return n_;
    }

    private void initFields() {
      messageType_ = com.nhekfqn.sample.server.proto.Protocol.MessageType.pong;
      n_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasN()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, n_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, n_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.nhekfqn.sample.server.proto.Protocol.Pong parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.Pong parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.Pong parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.Pong parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.Pong parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.Pong parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.Pong parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.Pong parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.Pong parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.nhekfqn.sample.server.proto.Protocol.Pong parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.nhekfqn.sample.server.proto.Protocol.Pong prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.nhekfqn.sample.server.proto.Pong}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.nhekfqn.sample.server.proto.Protocol.PongOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nhekfqn.sample.server.proto.Protocol.internal_static_com_nhekfqn_sample_server_proto_Pong_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nhekfqn.sample.server.proto.Protocol.internal_static_com_nhekfqn_sample_server_proto_Pong_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nhekfqn.sample.server.proto.Protocol.Pong.class, com.nhekfqn.sample.server.proto.Protocol.Pong.Builder.class);
      }

      // Construct using com.nhekfqn.sample.server.proto.Protocol.Pong.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageType_ = com.nhekfqn.sample.server.proto.Protocol.MessageType.pong;
        bitField0_ = (bitField0_ & ~0x00000001);
        n_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nhekfqn.sample.server.proto.Protocol.internal_static_com_nhekfqn_sample_server_proto_Pong_descriptor;
      }

      public com.nhekfqn.sample.server.proto.Protocol.Pong getDefaultInstanceForType() {
        return com.nhekfqn.sample.server.proto.Protocol.Pong.getDefaultInstance();
      }

      public com.nhekfqn.sample.server.proto.Protocol.Pong build() {
        com.nhekfqn.sample.server.proto.Protocol.Pong result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nhekfqn.sample.server.proto.Protocol.Pong buildPartial() {
        com.nhekfqn.sample.server.proto.Protocol.Pong result = new com.nhekfqn.sample.server.proto.Protocol.Pong(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.n_ = n_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nhekfqn.sample.server.proto.Protocol.Pong) {
          return mergeFrom((com.nhekfqn.sample.server.proto.Protocol.Pong)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nhekfqn.sample.server.proto.Protocol.Pong other) {
        if (other == com.nhekfqn.sample.server.proto.Protocol.Pong.getDefaultInstance()) return this;
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasN()) {
          setN(other.getN());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasN()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nhekfqn.sample.server.proto.Protocol.Pong parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nhekfqn.sample.server.proto.Protocol.Pong) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.nhekfqn.sample.server.proto.MessageType messageType = 1 [default = pong];
      private com.nhekfqn.sample.server.proto.Protocol.MessageType messageType_ = com.nhekfqn.sample.server.proto.Protocol.MessageType.pong;
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.MessageType messageType = 1 [default = pong];</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.MessageType messageType = 1 [default = pong];</code>
       */
      public com.nhekfqn.sample.server.proto.Protocol.MessageType getMessageType() {
        return messageType_;
      }
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.MessageType messageType = 1 [default = pong];</code>
       */
      public Builder setMessageType(com.nhekfqn.sample.server.proto.Protocol.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.nhekfqn.sample.server.proto.MessageType messageType = 1 [default = pong];</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = com.nhekfqn.sample.server.proto.Protocol.MessageType.pong;
        onChanged();
        return this;
      }

      // required int32 n = 2;
      private int n_ ;
      /**
       * <code>required int32 n = 2;</code>
       */
      public boolean hasN() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 n = 2;</code>
       */
      public int getN() {
        return n_;
      }
      /**
       * <code>required int32 n = 2;</code>
       */
      public Builder setN(int value) {
        bitField0_ |= 0x00000002;
        n_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 n = 2;</code>
       */
      public Builder clearN() {
        bitField0_ = (bitField0_ & ~0x00000002);
        n_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.nhekfqn.sample.server.proto.Pong)
    }

    static {
      defaultInstance = new Pong(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.nhekfqn.sample.server.proto.Pong)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nhekfqn_sample_server_proto_BaseMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_nhekfqn_sample_server_proto_BaseMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nhekfqn_sample_server_proto_Ping_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_nhekfqn_sample_server_proto_Ping_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nhekfqn_sample_server_proto_Pong_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_nhekfqn_sample_server_proto_Pong_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Protocol.proto\022\037com.nhekfqn.sample.ser" +
      "ver.proto\"\272\001\n\013BaseMessage\022A\n\013messageType" +
      "\030\001 \002(\0162,.com.nhekfqn.sample.server.proto" +
      ".MessageType\0223\n\004ping\030\002 \001(\0132%.com.nhekfqn" +
      ".sample.server.proto.Ping\0223\n\004pong\030\003 \001(\0132" +
      "%.com.nhekfqn.sample.server.proto.Pong\"_" +
      "\n\004Ping\022G\n\013messageType\030\001 \001(\0162,.com.nhekfq" +
      "n.sample.server.proto.MessageType:\004ping\022" +
      "\016\n\006userId\030\002 \002(\t\"Z\n\004Pong\022G\n\013messageType\030\001" +
      " \001(\0162,.com.nhekfqn.sample.server.proto.M",
      "essageType:\004pong\022\t\n\001n\030\002 \002(\005*!\n\013MessageTy" +
      "pe\022\010\n\004ping\020\001\022\010\n\004pong\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_nhekfqn_sample_server_proto_BaseMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_nhekfqn_sample_server_proto_BaseMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_nhekfqn_sample_server_proto_BaseMessage_descriptor,
              new java.lang.String[] { "MessageType", "Ping", "Pong", });
          internal_static_com_nhekfqn_sample_server_proto_Ping_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_nhekfqn_sample_server_proto_Ping_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_nhekfqn_sample_server_proto_Ping_descriptor,
              new java.lang.String[] { "MessageType", "UserId", });
          internal_static_com_nhekfqn_sample_server_proto_Pong_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_nhekfqn_sample_server_proto_Pong_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_nhekfqn_sample_server_proto_Pong_descriptor,
              new java.lang.String[] { "MessageType", "N", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
